/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactSubmission {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phoneNumber' : [] | [string],
}
export interface DocumentRequirement {
  'id' : bigint,
  'name' : string,
  'description' : [] | [string],
  'requiredFor' : Array<string>,
}
export interface Inquiry {
  'id' : bigint,
  'name' : string,
  'timestamp' : bigint,
  'phoneNumber' : string,
  'serviceNeeded' : string,
}
export interface Service {
  'id' : bigint,
  'title' : string,
  'active' : boolean,
  'description' : string,
  'category' : string,
  'price' : [] | [bigint],
}
export interface _SERVICE {
  'addDocumentRequirement' : ActorMethod<
    [string, [] | [string], Array<string>],
    bigint
  >,
  'addService' : ActorMethod<
    [string, string, string, boolean, [] | [bigint]],
    bigint
  >,
  'deleteContactSubmission' : ActorMethod<[bigint], undefined>,
  'deleteDocumentRequirement' : ActorMethod<[bigint], undefined>,
  'deleteInquiry' : ActorMethod<[bigint], undefined>,
  'deleteService' : ActorMethod<[bigint], undefined>,
  'getAllContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getAllDocumentRequirements' : ActorMethod<[], Array<DocumentRequirement>>,
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getDocumentRequirementsForService' : ActorMethod<
    [string],
    Array<DocumentRequirement>
  >,
  'getInquiriesByService' : ActorMethod<[string], Array<Inquiry>>,
  'getInquiry' : ActorMethod<[bigint], [] | [Inquiry]>,
  'getServicesByCategory' : ActorMethod<[string], Array<Service>>,
  'submitContactForm' : ActorMethod<
    [string, string, string, [] | [string]],
    bigint
  >,
  'submitInquiry' : ActorMethod<[string, string, string], bigint>,
  'updateDocumentRequirement' : ActorMethod<
    [bigint, [] | [string], [] | [string], [] | [Array<string>]],
    undefined
  >,
  'updateService' : ActorMethod<
    [
      bigint,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [boolean],
      [] | [bigint],
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];