/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Nat,
  'phoneNumber' : IDL.Opt(IDL.Text),
});
export const DocumentRequirement = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Opt(IDL.Text),
  'requiredFor' : IDL.Vec(IDL.Text),
});
export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'timestamp' : IDL.Nat,
  'phoneNumber' : IDL.Text,
  'serviceNeeded' : IDL.Text,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'active' : IDL.Bool,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  'addDocumentRequirement' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'addService' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Opt(IDL.Nat)],
      [IDL.Nat],
      [],
    ),
  'deleteContactSubmission' : IDL.Func([IDL.Nat], [], []),
  'deleteDocumentRequirement' : IDL.Func([IDL.Nat], [], []),
  'deleteInquiry' : IDL.Func([IDL.Nat], [], []),
  'deleteService' : IDL.Func([IDL.Nat], [], []),
  'getAllContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getAllDocumentRequirements' : IDL.Func(
      [],
      [IDL.Vec(DocumentRequirement)],
      ['query'],
    ),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getDocumentRequirementsForService' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DocumentRequirement)],
      ['query'],
    ),
  'getInquiriesByService' : IDL.Func([IDL.Text], [IDL.Vec(Inquiry)], ['query']),
  'getInquiry' : IDL.Func([IDL.Nat], [IDL.Opt(Inquiry)], ['query']),
  'getServicesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Service)], ['query']),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'submitInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'updateDocumentRequirement' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Vec(IDL.Text)),
      ],
      [],
      [],
    ),
  'updateService' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Bool),
        IDL.Opt(IDL.Nat),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Nat,
    'phoneNumber' : IDL.Opt(IDL.Text),
  });
  const DocumentRequirement = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
    'requiredFor' : IDL.Vec(IDL.Text),
  });
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'timestamp' : IDL.Nat,
    'phoneNumber' : IDL.Text,
    'serviceNeeded' : IDL.Text,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'active' : IDL.Bool,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    'addDocumentRequirement' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'addService' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Opt(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'deleteContactSubmission' : IDL.Func([IDL.Nat], [], []),
    'deleteDocumentRequirement' : IDL.Func([IDL.Nat], [], []),
    'deleteInquiry' : IDL.Func([IDL.Nat], [], []),
    'deleteService' : IDL.Func([IDL.Nat], [], []),
    'getAllContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getAllDocumentRequirements' : IDL.Func(
        [],
        [IDL.Vec(DocumentRequirement)],
        ['query'],
      ),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getDocumentRequirementsForService' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DocumentRequirement)],
        ['query'],
      ),
    'getInquiriesByService' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Inquiry)],
        ['query'],
      ),
    'getInquiry' : IDL.Func([IDL.Nat], [IDL.Opt(Inquiry)], ['query']),
    'getServicesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Service)],
        ['query'],
      ),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'submitInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'updateDocumentRequirement' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Vec(IDL.Text)),
        ],
        [],
        [],
      ),
    'updateService' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Bool),
          IDL.Opt(IDL.Nat),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };